<a href="https://colab.research.google.com/github/Ernesto1602/Projects/blob/main/An%C3%A1lisis_de_Datos_con_Np%26pd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1.4,4.2,5.3,6.5],dtype='int')
print(a)
type(a)

[1 4 5 6]


numpy.ndarray

In [ ]:
import numpy as np
import pandas as pd
matriz = list(np.random.rand(100,2)*10)
tabla = pd.DataFrame(matriz,columns=['presion','temperatura'])
tabla.to_csv('examen2.csv')

In [ ]:
matriz

[array([5.2824997 , 2.22404968]),
 array([8.3935393, 0.7838107]),
 array([6.41985362, 8.36067709]),
 array([5.16012081, 4.30407664]),
 array([7.70176626, 3.72294757]),
 array([8.6003791 , 3.48196234]),
 array([0.70085991, 5.03486881]),
 array([3.00557918, 5.36427821]),
 array([0.25144051, 6.02125063]),
 array([0.99713318, 0.90650226]),
 array([0.13776524, 8.80401063]),
 array([8.51802454, 8.41224546]),
 array([6.80165997, 7.06400161]),
 array([9.04044515, 2.40422778]),
 array([8.68781952, 0.32768592]),
 array([4.11383307, 8.60363382]),
 array([5.13689549, 0.431722  ]),
 array([8.23225544, 4.70636417]),
 array([7.96280773, 9.39824882]),
 array([3.91592327, 2.00271706]),
 array([0.21938182, 2.55561654]),
 array([5.12308492, 0.49805915]),
 array([7.56800107, 3.66848387]),
 array([6.73359451, 3.16800733]),
 array([3.62428708, 7.24890314]),
 array([5.21190689, 9.78710096]),
 array([3.06730579, 7.10737928]),
 array([0.75199839, 7.64267481]),
 array([5.72519962, 3.21944216]),
 array([9.682220

In [ ]:
print(l1)

[[8.248241122047471, 7.298588663831938, 0.7184705734242713, 4.110636422122974, 7.614667602307646, 0.6718188170316375, 6.030702914369709, 2.1995880517400135, 5.29244987780862, 8.16021252208578, 5.728379506858557, 2.1401699545498953, 2.4875404504157563, 3.193095761299003, 4.66293118394986, 5.883569331279233, 4.809973459624545, 9.149123723695054, 3.8076753207613767, 8.4926924866473, 1.6171431444140727, 1.126782630214015, 1.5803830995978219, 2.9340324288142683, 7.668835206089961, 5.8468924030187175, 9.524674910003386, 1.28465669914836, 3.3173301753376916, 3.9301142119392596, 2.044881675857302, 1.1347493762347716, 6.084514775731181, 2.723221415831399, 7.2458736357620745, 0.7991989621572071, 1.8482272397049837, 9.953166346887963, 7.746179228241655, 0.6106943363876915, 8.475052104766242, 5.283952267763599, 2.765096469326079, 2.219251915460508, 3.8349913336605024, 8.143184658454345, 5.033702427299072, 7.756251565249802, 3.4848903441789014, 2.229815953834129, 4.815607598712635, 4.81570345300345

In [ ]:
tabla = pd.DataFrame(l1,columns=['presion','temperatura'])

ValueError: ignored

In [ ]:
list1 = [1,3,4,5,6]
dicc = (2,4,5)
sset = {2,3,4}
x = np.array(sset)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
a = np.array([8,3,4])
print(a)

[8 3 4]


In [ ]:
a.sort()

In [ ]:
a

array([3, 4, 8])

In [ ]:
print(a)

[3 4 8]


In [ ]:
L = [2,3,7,5]
L.sort() #ordenar es una función de la librería numpy y funciona con listas.


In [ ]:
L

[2, 3, 5, 7]

In [ ]:
from numpy import fft

In [ ]:
fft??

In [ ]:
fft.fftfreq??

In [ ]:
fft.fftfreq??

In [ ]:
from numpy import linalg

In [ ]:
linalg??

In [ ]:

C = np.array([[1,2,4],[2,4,5]])
D = np.transpose(C)

In [ ]:
print(C)

[[1 2 4]
 [2 4 5]]


In [ ]:
print(D)

[[1 2]
 [2 4]
 [4 5]]


In [ ]:
Matriz = np.identity(4,dtype = 'int')

In [ ]:
print(Matriz)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
Matriz2 = Matriz*2

In [ ]:
Matriz2

array([[2, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 2]])

In [ ]:
matriz3 = np.eye(4,2)

In [ ]:
print(matriz3)

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]]


In [ ]:
l = []
for i in range(0,10,2):
  l.append(i)
print(l)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98]


In [ ]:
vector1 = np.linspace(1,100,50,dtype=int)
print(vector1)

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97 100]


In [ ]:
vector1 = np.linspace(1,10,100)

In [ ]:
vector2 = np.round(vector1,2)
print(vector2)

[ 1.    1.09  1.18  1.27  1.36  1.45  1.55  1.64  1.73  1.82  1.91  2.
  2.09  2.18  2.27  2.36  2.45  2.55  2.64  2.73  2.82  2.91  3.    3.09
  3.18  3.27  3.36  3.45  3.55  3.64  3.73  3.82  3.91  4.    4.09  4.18
  4.27  4.36  4.45  4.55  4.64  4.73  4.82  4.91  5.    5.09  5.18  5.27
  5.36  5.45  5.55  5.64  5.73  5.82  5.91  6.    6.09  6.18  6.27  6.36
  6.45  6.55  6.64  6.73  6.82  6.91  7.    7.09  7.18  7.27  7.36  7.45
  7.55  7.64  7.73  7.82  7.91  8.    8.09  8.18  8.27  8.36  8.45  8.55
  8.64  8.73  8.82  8.91  9.    9.09  9.18  9.27  9.36  9.45  9.55  9.64
  9.73  9.82  9.91 10.  ]


In [ ]:
vector3 = np.linspace(1,5,100)

In [ ]:
vector4 = np.round(vector3)

In [ ]:
matriz = np.array([[vector2],[vector4]]) #crear una matriz utilizando vectores con linspace

In [ ]:
matriz

array([[[ 1.  ,  1.09,  1.18,  1.27,  1.36,  1.45,  1.55,  1.64,  1.73,
          1.82,  1.91,  2.  ,  2.09,  2.18,  2.27,  2.36,  2.45,  2.55,
          2.64,  2.73,  2.82,  2.91,  3.  ,  3.09,  3.18,  3.27,  3.36,
          3.45,  3.55,  3.64,  3.73,  3.82,  3.91,  4.  ,  4.09,  4.18,
          4.27,  4.36,  4.45,  4.55,  4.64,  4.73,  4.82,  4.91,  5.  ,
          5.09,  5.18,  5.27,  5.36,  5.45,  5.55,  5.64,  5.73,  5.82,
          5.91,  6.  ,  6.09,  6.18,  6.27,  6.36,  6.45,  6.55,  6.64,
          6.73,  6.82,  6.91,  7.  ,  7.09,  7.18,  7.27,  7.36,  7.45,
          7.55,  7.64,  7.73,  7.82,  7.91,  8.  ,  8.09,  8.18,  8.27,
          8.36,  8.45,  8.55,  8.64,  8.73,  8.82,  8.91,  9.  ,  9.09,
          9.18,  9.27,  9.36,  9.45,  9.55,  9.64,  9.73,  9.82,  9.91,
         10.  ]],

       [[ 1.  ,  1.  ,  1.  ,  1.  ,  1.  ,  1.  ,  1.  ,  1.  ,  1.  ,
          1.  ,  1.  ,  1.  ,  1.  ,  2.  ,  2.  ,  2.  ,  2.  ,  2.  ,
          2.  ,  2.  ,  2.  ,  2.  ,  2.  ,  

In [ ]:
a = np.array([[1,3,5],[0,1,3],[0,3,4]])
b = np.array([[0,2,4],[0,2,4],[1,3,4]])

In [ ]:
a

array([[1, 3, 5],
       [0, 1, 3],
       [0, 3, 4]])

In [ ]:
c = np.concatenate((a,b),1) #colocamos 1 al concatenar filas con filas, y nada si queremos concatenar columnas con columnas

In [ ]:
c

array([[1, 3, 5, 0, 2, 4],
       [0, 1, 3, 0, 2, 4],
       [0, 3, 4, 1, 3, 4]])

# Análisis de datos con Pandas

In [ ]:
# Indexación

import numpy as np
import pandas as pd
vector1 = np.linspace(1,5,5,dtype='int')

In [ ]:
ind1 = pd.Series(vector1,index = ['a','b','c','d','e'])

In [ ]:
ind1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
ind1['e']

5

In [ ]:
lista1 = ['ruben', 'tigre', 'marcelo'] #indexar = etiquetar
ind2 = pd.Series(lista1,index=['persona','gato','niño'])

In [ ]:
ind2

persona      ruben
gato         tigre
niño       marcelo
dtype: object

In [ ]:
alumnos = [{'nombre' : 'María', 'edad' : 19, 'color_fa': 'turquesa'},{'nombre' : 'Marcela', 'edad' : 20, 'color_fa' : 'celeste'},{'nombre' : 'Juan Carlos', 'edad' : 17, 'color_fa': 'rojo'}]

In [ ]:
tabla_alumnos = pd.DataFrame(alumnos)

In [ ]:
tabla_alumnos

nombre  edad  color_fa
0        María    19  turquesa
1      Marcela    20   celeste
2  Juan Carlos    17      rojo

In [ ]:
#subir los archivos a python

In [ ]:
import pandas as pd


In [ ]:
tabla_notas = pd.read_csv('notas.csv')

In [ ]:
tabla_notas.head(2)

Unnamed: 0   Nombre  Edad       Sexo  Nota1  Nota2  Nota3  Aula
0           0    Marco    14  Masculino   17.0   13.0   11.0  Roja
1           1  Alberto    16  Masculino   14.0   13.0   14.0  Roja

In [ ]:
tabla_notas.tail(3)

Unnamed: 0    Nombre  Edad      Sexo  Nota1  Nota2  Nota3  Aula
17          17   Juliana    17  Femenino   13.0   17.0   18.0  Roja
18          18  Estefani    14  Femenino   17.0   14.0   14.4  Roja
19          19   Julissa    15  Femenino   19.0   19.0   14.5  Roja

In [ ]:
print(len(tabla_notas))

20


In [ ]:
columnas = tabla_notas.columns

In [ ]:
print(tabla_notas.columns)

Index(['Unnamed: 0', 'Nombre', 'Edad', 'Sexo', 'Nota1', 'Nota2', 'Nota3',
       'Aula'],
      dtype='object')


In [ ]:
type(columnas)

pandas.core.indexes.base.Index

In [ ]:
Nombres = tabla_notas['Nombre']

In [ ]:
print(Nombres)

0           Marco
1         Alberto
2          Roxana
3           Mario
4           Pedro
5     Juan Carlos
6          Julian
7           Jorge
8         Esteban
9      Juan Diego
10      Maricielo
11          María
12         Matías
13       Fernanda
14          Mateo
15        Mariana
16      Petronila
17        Juliana
18       Estefani
19        Julissa
Name: Nombre, dtype: object


In [ ]:
Nombres = list(Nombres)

In [ ]:
print(Nombres)

['Marco', 'Alberto', 'Roxana', 'Mario', 'Pedro', 'Juan Carlos', 'Julian', 'Jorge', 'Esteban', 'Juan Diego', 'Maricielo', 'María', 'Matías', 'Fernanda', 'Mateo', 'Mariana', 'Petronila', 'Juliana', 'Estefani', 'Julissa']


In [ ]:
import numpy as np
Nombres = np.array(Nombres)

In [ ]:
type(Nombres)

numpy.ndarray

In [ ]:
print(tabla_notas['Nombre'][0:4]) # el índice final, no ha sido tomado como valor

0      Marco
1    Alberto
2     Roxana
3      Mario
Name: Nombre, dtype: object


In [ ]:
Nombres_2 = tabla_notas['Nombre'][0:4]

In [ ]:
Nombres_2

0      Marco
1    Alberto
2     Roxana
3      Mario
Name: Nombre, dtype: object

In [ ]:
#funcion iloc--llamar a una o a varias filas por el valor de su índice

print(tabla_notas.iloc[0])


Unnamed: 0            0
Nombre            Marco
Edad                 14
Sexo          Masculino
Nota1                17
Nota2                13
Nota3                11
Aula               Roja
Name: 0, dtype: object


In [ ]:
print(tabla_notas.iloc[0:4])

   Unnamed: 0   Nombre  Edad       Sexo  Nota1  Nota2  Nota3  Aula
0           0    Marco    14  Masculino   17.0   13.0   11.0  Roja
1           1  Alberto    16  Masculino   14.0   13.0   14.0  Roja
2           2   Roxana    15   Femenino   15.0   14.0   15.0  Roja
3           3    Mario    15  Masculino   16.0   13.0   11.0  Roja


In [ ]:
##Filtrar valores en las tablas

In [ ]:
#¿cuántos alumnos hay en el aula roja?
aula_roja = tabla_notas.loc[tabla_notas['Aula'] == 'Roja']

In [ ]:
print(len(aula_roja))

13


In [ ]:
tabla_notas.head(3)

Unnamed: 0   Nombre  Edad       Sexo  Nota1  Nota2  Nota3  Aula
0           0    Marco    14  Masculino   17.0   13.0   11.0  Roja
1           1  Alberto    16  Masculino   14.0   13.0   14.0  Roja
2           2   Roxana    15   Femenino   15.0   14.0   15.0  Roja

In [ ]:
tabla_notas = tabla_notas.drop(columns = ['Unnamed: 0'])

In [ ]:
tabla_notas.head(3)

Nombre  Edad       Sexo  Nota1  Nota2  Nota3  Aula
0    Marco    14  Masculino   17.0   13.0   11.0  Roja
1  Alberto    16  Masculino   14.0   13.0   14.0  Roja
2   Roxana    15   Femenino   15.0   14.0   15.0  Roja

In [ ]:
#Del aula roja, ¿cuántos alumnos son hombres?
# filro lógico----Es decir : Es un filtro que cumple una función lógica|| & : Significa Sí y solo sí
hombres_aula_roja = tabla_notas.loc[(tabla_notas['Sexo'] == 'Masculino')&(tabla_notas['Aula']== 'Roja')]

In [ ]:
print(len(hombres_aula_roja))

7


In [ ]:
len(aula_roja)-len(hombres_aula_roja)

6

In [ ]:
#filtro con | : or #o se cumple una condición o la otra  |||
hombres_o_verde = tabla_notas.loc[(tabla_notas['Sexo'] == 'Masculino')|(tabla_notas['Aula']== 'Verde')]

In [ ]:
hombres_o_verde

Nombre  Edad       Sexo  Nota1      Nota2  Nota3   Aula
0         Marco    14  Masculino   17.0  13.000000   11.0   Roja
1       Alberto    16  Masculino   14.0  13.000000   14.0   Roja
3         Mario    15  Masculino   16.0  13.000000   11.0   Roja
4         Pedro    15  Masculino   11.0  13.500000   13.0  Verde
5   Juan Carlos    16  Masculino   14.8  13.600000   13.1  Verde
6        Julian    16  Masculino   14.6  11.000000   11.0   Roja
7         Jorge    15  Masculino   14.4  12.333333   13.3  Verde
8       Esteban    15  Masculino   10.0  13.083333   12.0  Verde
9    Juan Diego    16  Masculino   14.0  14.000000   13.5   Roja
10    Maricielo    14  Masculino   13.8  16.000000   16.0   Roja
12       Matías    16  Masculino   13.4  17.833333   15.0   Roja
14        Mateo    15  Masculino   19.0  18.833333   18.0  Verde
15      Mariana    15   Femenino   14.0  20.000000   11.0  Verde
16    Petronila    16   Femenino   12.6  16.000000   12.0  Verde

In [ ]:
estadisticas = tabla_notas.describe()

In [ ]:
print(np.round(estadisticas,0))

       Edad  Nota1  Nota2  Nota3
count  20.0   20.0   20.0   20.0
mean   15.0   14.0   15.0   14.0
std     1.0    2.0    3.0    2.0
min    14.0   10.0   11.0   11.0
25%    15.0   13.0   13.0   12.0
50%    15.0   14.0   14.0   14.0
75%    16.0   15.0   16.0   15.0
max    17.0   19.0   20.0   18.0


In [ ]:
tabla_notas2 = tabla_notas.sort_values('Edad')

In [ ]:
tabla_notas2.head(5)

Nombre  Edad       Sexo  Nota1      Nota2  Nota3   Aula
0       Marco    14  Masculino   17.0  13.000000   11.0   Roja
10  Maricielo    14  Masculino   13.8  16.000000   16.0   Roja
18   Estefani    14   Femenino   17.0  14.000000   14.4   Roja
15    Mariana    15   Femenino   14.0  20.000000   11.0  Verde
14      Mateo    15  Masculino   19.0  18.833333   18.0  Verde

In [ ]:
tabla_notas.sort_values('Nombre')

Nombre  Edad       Sexo  Nota1      Nota2  Nota3   Aula
1       Alberto    16  Masculino   14.0  13.000000   14.0   Roja
8       Esteban    15  Masculino   10.0  13.083333   12.0  Verde
18     Estefani    14   Femenino   17.0  14.000000   14.4   Roja
13     Fernanda    16   Femenino   11.0  15.000000   17.0   Roja
7         Jorge    15  Masculino   14.4  12.333333   13.3  Verde
5   Juan Carlos    16  Masculino   14.8  13.600000   13.1  Verde
9    Juan Diego    16  Masculino   14.0  14.000000   13.5   Roja
6        Julian    16  Masculino   14.6  11.000000   11.0   Roja
17      Juliana    17   Femenino   13.0  17.000000   18.0   Roja
19      Julissa    15   Femenino   19.0  19.000000   14.5   Roja
0         Marco    14  Masculino   17.0  13.000000   11.0   Roja
15      Mariana    15   Femenino   14.0  20.000000   11.0  Verde
10    Maricielo    14  Masculino   13.8  16.000000   16.0   Roja
3         Mario    15  Masculino   16.0  13.000000   11.0   Roja
11        María    17   Femenino   13.6  12.000000   13.7   Roja
14        Mateo    15  Masculino   19.0  18.833333   18.0  Verde
12       Matías    16  Masculino   13.4  17.833333   15.0   Roja
4         Pedro    15  Masculino   11.0  13.500000   13.0  Verde
16    Petronila    16   Femenino   12.6  16.000000   12.0  Verde
2        Roxana    15   Femenino   15.0  14.000000   15.0   Roja

In [ ]:
tabla_notas.sort_values('Edad',ascending= False)

Nombre  Edad       Sexo  Nota1      Nota2  Nota3   Aula
17      Juliana    17   Femenino   13.0  17.000000   18.0   Roja
11        María    17   Femenino   13.6  12.000000   13.7   Roja
1       Alberto    16  Masculino   14.0  13.000000   14.0   Roja
16    Petronila    16   Femenino   12.6  16.000000   12.0  Verde
13     Fernanda    16   Femenino   11.0  15.000000   17.0   Roja
12       Matías    16  Masculino   13.4  17.833333   15.0   Roja
9    Juan Diego    16  Masculino   14.0  14.000000   13.5   Roja
6        Julian    16  Masculino   14.6  11.000000   11.0   Roja
5   Juan Carlos    16  Masculino   14.8  13.600000   13.1  Verde
7         Jorge    15  Masculino   14.4  12.333333   13.3  Verde
8       Esteban    15  Masculino   10.0  13.083333   12.0  Verde
4         Pedro    15  Masculino   11.0  13.500000   13.0  Verde
3         Mario    15  Masculino   16.0  13.000000   11.0   Roja
14        Mateo    15  Masculino   19.0  18.833333   18.0  Verde
15      Mariana    15   Femenino   14.0  20.000000   11.0  Verde
2        Roxana    15   Femenino   15.0  14.000000   15.0   Roja
19      Julissa    15   Femenino   19.0  19.000000   14.5   Roja
18     Estefani    14   Femenino   17.0  14.000000   14.4   Roja
0         Marco    14  Masculino   17.0  13.000000   11.0   Roja
10    Maricielo    14  Masculino   13.8  16.000000   16.0   Roja

In [ ]:
tabla_notas['Nota2'] = np.round(tabla_notas['Nota2'],0)

In [ ]:
tabla_notas.head(5)

Nombre  Edad       Sexo  Nota1  Nota2  Nota3   Aula
0    Marco    14  Masculino   17.0   13.0   11.0   Roja
1  Alberto    16  Masculino   14.0   13.0   14.0   Roja
2   Roxana    15   Femenino   15.0   14.0   15.0   Roja
3    Mario    15  Masculino   16.0   13.0   11.0   Roja
4    Pedro    15  Masculino   11.0   14.0   13.0  Verde

In [ ]:
tabla_notas['Promedio'] = (tabla_notas['Nota1']+tabla_notas['Nota2']+tabla_notas['Nota3'])/3

In [ ]:
tabla_notas.head(5)

Nombre  Edad       Sexo  Nota1  Nota2  Nota3   Aula   Promedio
0    Marco    14  Masculino   17.0   13.0   11.0   Roja  13.666667
1  Alberto    16  Masculino   14.0   13.0   14.0   Roja  13.666667
2   Roxana    15   Femenino   15.0   14.0   15.0   Roja  14.666667
3    Mario    15  Masculino   16.0   13.0   11.0   Roja  13.333333
4    Pedro    15  Masculino   11.0   14.0   13.0  Verde  12.666667

In [ ]:
tabla_notas['Promedio'] = np.round(tabla_notas['Promedio'],2)

In [ ]:
tabla_notas.head(5)

Nombre  Edad       Sexo  Nota1  ...  Promedio  Promedio  Promedio  Promedio
0    Marco    14  Masculino   17.0  ...     13.67     13.67     13.67     13.67
1  Alberto    16  Masculino   14.0  ...     13.67     13.67     13.67     13.67
2   Roxana    15   Femenino   15.0  ...     14.67     14.67     14.67     14.67
3    Mario    15  Masculino   16.0  ...     13.33     13.33     13.33     13.33
4    Pedro    15  Masculino   11.0  ...     12.67     12.67     12.67     12.67

[5 rows x 11 columns]

In [ ]:
columnas = list(tabla_notas.columns.values)
tabla_notas2 = tabla_notas[columnas[0:6]+[columnas[-1]]+columnas[6:7]]

In [ ]:
tabla_notas = tabla_notas.drop(columns = ['Promedio'])

In [ ]:
tabla_notas.head(3)

Nombre  Edad       Sexo  Nota1  Nota2  Nota3  Aula
0    Marco    14  Masculino   17.0   13.0   11.0  Roja
1  Alberto    16  Masculino   14.0   13.0   14.0  Roja
2   Roxana    15   Femenino   15.0   14.0   15.0  Roja

In [ ]:
tabla_notas['Promedio'] = (tabla_notas['Nota1']+tabla_notas['Nota2']+tabla_notas['Nota3'])/3

In [ ]:
tabla_notas['Promedio'] = np.round(tabla_notas['Promedio'],2)

In [ ]:
tabla_notas.head(3)

Nombre  Edad       Sexo  Nota1  Nota2  Nota3  Aula  Promedio
0    Marco    14  Masculino   17.0   13.0   11.0  Roja     13.67
1  Alberto    16  Masculino   14.0   13.0   14.0  Roja     13.67
2   Roxana    15   Femenino   15.0   14.0   15.0  Roja     14.67

In [ ]:
columnas = list(tabla_notas.columns.values)
tabla_notas3 = tabla_notas[columnas[0:6]+[columnas[-1]]+[columnas[6]]]

In [ ]:
tabla_notas3.head(3)

Nombre  Edad       Sexo  Nota1  Nota2  Nota3  Promedio  Aula
0    Marco    14  Masculino   17.0   13.0   11.0     13.67  Roja
1  Alberto    16  Masculino   14.0   13.0   14.0     13.67  Roja
2   Roxana    15   Femenino   15.0   14.0   15.0     14.67  Roja

In [ ]:
print(columnas)

['Nombre', 'Edad', 'Sexo', 'Nota1', 'Nota2', 'Nota3', 'Aula', 'Promedio']


In [ ]:
print(tabla_notas.columns.values)

['Nombre' 'Edad' 'Sexo' 'Nota1' 'Nota2' 'Nota3' 'Aula' 'Promedio']
